Repository 1stdibs/dibs-vg, pull requests merged in 2018-10, with the labels that each got.

#178 feat: TRADE-3096 chair-check.svg
  list.json
  sample/compiled/sample.js
  sample/compiled/sample.js.map
  src/chair-check.svg
Labels: ready for review

#180 feat: TRADE-2882 professional-wreath graphic
  list.json
  src/professional-wreath.svg
Labels: don't merge

#181 feat: compile style attributes
  package.json
  sample/compiled/sample.js
  sample/compiled/sample.js.map
  scripts/htmlToReact.js
  yarn.lock
Labels: question, ready for review

#182 feat: TRADE-3243 update circle-question-mark icons
  list.json
  src/circle-question-mark-empty.svg
  src/circle-question-mark-filled.svg
Labels: ready for review

#185 feat: TXN-4441: added note-message and note-message-unread icons
  list.json
  src/note-message-unread.svg
  src/note-message.svg
Labels: ready for review

#187 fix: TRADE-3271 fix buyer protection icon
  src/buyer-assurance.svg
Labels: ready for review
